logging:
  level:
    '[com.subrutin.catalogue.service]': TRACE

spring:
  datasource:
    hikari:
      connection-timeout: 600000
      idle-timeout: 600000
      max-lifetime: 1800000
    url: jdbc:postgresql://127.0.0.1/book_catalogue
    username: subrutin
    password: subrutin
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

app:
  currency: IDR
  timezone: Asia/Jakarta
  welcome-text: Hello World from Spring Book (This text comes from default properties)
cloud:
  api-key: '${CLOUD_KEY}'
server:
  port: 8081
  
---
spring:
  config:
    activate:
      on-profile:
      - development
  
server:
  port: 8082
  
app:
  welcome-text: Welcome to development profiles
  
---
spring:
  config:
    activate:
      on-profile:
      - test
  
server:
  port: 8083
  
app:
  welcome-text: Welcome to test profiles
  
---
spring:
  config:
    activate:
      on-profile:
      - production
  
server:
  port: 80
  
app:
  welcome-text: Welcome to production profiles
